import 'package:myapp/models/project_model.dart';

List<ProjectModel> projects = [
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
  ProjectModel(title: 'Hello World', category: 'Experments'),
];
